name: flutter_course_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.1
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1


#  flutter_native_splash: ^2.2.19
#
#flutter_native_splash:
#  color: "#f7f6f1"
#  color_dark: "#272727"
#  image: assets/images/splash.png
#  image_dark: assets/images/splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/images/dashboard/
    - assets/images/on_boarding_images/
    - assets/images/welcome_screen/
  #  - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
